### ISSUE TITLE
Great job, did you just win the Nobel Prize!

### ISSUE THREAD

**Issue by Enderfga** [jiahaoli57/Call-for-Reviewers#8]
I suddenly realized that your avatar looks a lot like a poster for the Nobel Prize, which is very interesting. Is it hand-drawn or AI-generated?

**Comment by jiahaoli57** [comment]
LOL

![nb_prize_small](https://github.com/user-attachments/assets/33d3708e-7245-4b3d-8b58-3c096f0f455d)

**Comment by Enderfga** [comment]
Can you share how you made it?

**Comment by jiahaoli57** [comment]
A painter helped me draw it. I paid her 100 RMB last year. If you need, I can give you her WeChat or you can search her Xiaohongshu account "茜医综合".
